services:
  api:
    build: DockerfileAPI
    entrypoint: /bin/sh -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80"
    expose:
      - "80"
  website:
    build: DockerfileWebsite
    entrypoint: /bin/sh -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80"
    expose:
      - "80"
  caddy:
    image: caddy:2.9.1-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3307:3306"
    networks:
      - catnet
    restart: unless-stopped
