services:
  api:

  website:

  caddy:

  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3307:3306"
    networks:
      - catnet
    restart: unless-stopped
